apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    argocd.argoproj.io/sync-options: Validate=false
  labels:
    app: {{ .Values.name }}
  name: {{ .Values.name }}
  {{- if .Values.namespace }}
  namespace: {{ .Values.namespace }}
  {{- end }}
spec:
  port:
    targetPort: "{{ .Values.servicePort }}-tcp"
  tls:
    termination: edge
  to:
    kind: Service
    name: {{ .Values.name }}
    weight: 100
  wildcardPolicy: None
